import { MaintenanceTicket } from '@/types/maintenance';

export const MOCK_TICKETS: MaintenanceTicket[] = [
  {
    id: 'm1',
    title: 'Water leak under sink',
    description: 'Tenant reports steady drip from p-trap under kitchen sink. Cabinet is damp.',
    propertyId: 'p1',
    propertyName: 'Oak Street Apartments',
    unitId: 'u6',
    unitNumber: '3B',
    categoryId: 'plumbing',
    reportedBy: 'Jane Smith',
    reporterType: 'tenant',
    urgency: 'urgent',
    status: 'in_progress',
    vendorName: 'Rapid Plumbers Co.',
    estimatedCost: 350,
    accessPermission: true,
    preferredTime: 'anytime',
    createdAt: '2024-01-03 09:30 AM',
    updatedAt: '2024-01-03 11:45 AM'
  },
  {
    id: 'm2',
    title: 'HVAC not heating',
    description: 'Heater blowing cold air. Thermostat set to 72, temp is 64.',
    propertyId: 'p2',
    propertyName: 'Highland Lofts',
    unitId: 'u8',
    unitNumber: '102',
    categoryId: 'hvac',
    reportedBy: 'System Alert',
    reporterType: 'system',
    urgency: 'emergency',
    status: 'open',
    estimatedCost: 800,
    accessPermission: false, 
    createdAt: '2024-01-04 06:15 AM',
    updatedAt: '2024-01-04 06:15 AM'
  },
  {
    id: 'm3',
    title: 'Closet door off rack',
    description: 'Sliding door allows stuck.',
    propertyId: 'p3',
    propertyName: 'Sunset Duplex',
    unitId: 'u11',
    unitNumber: 'A',
    categoryId: 'general',
    reportedBy: 'David Wilson',
    reporterType: 'tenant',
    urgency: 'routine',
    status: 'waiting',
    vendorName: 'Handyman Joe',
    estimatedCost: 150,
    accessPermission: true,
    preferredTime: 'morning',
    createdAt: '2023-12-28 02:00 PM',
    updatedAt: '2024-01-02 10:00 AM'
  },
  {
    id: 'm4',
    title: 'Lobby light flickering',
    description: 'Main recessed light in entry hallway is strobing.',
    propertyId: 'p2',
    propertyName: 'Highland Lofts',
    unitId: undefined,
    unitNumber: 'Common Area',
    categoryId: 'electrical',
    reportedBy: 'Property Manager',
    reporterType: 'manager',
    urgency: 'routine',
    status: 'resolved',
    vendorName: 'Bright Spark Electric',
    estimatedCost: 200,
    actualCost: 185,
    accessPermission: false,
    createdAt: '2023-12-20',
    updatedAt: '2023-12-22'
  }
];

export const VENDORS = [
    { id: 'v1', name: 'Rapid Plumbers Co.', category: 'plumbing' },
    { id: 'v2', name: 'Bright Spark Electric', category: 'electrical' },
    { id: 'v3', name: 'Handyman Joe', category: 'general' },
    { id: 'v4', name: 'Cool Air HVAC', category: 'hvac' },
];
