import { Tenant } from '@/shared/types/tenant';

export const MOCK_TENANTS: Tenant[] = [
  {
    id: 't1',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    phone: '555-0101',
    propertyId: 'p1',
    propertyName: 'Oak Street Apartments',
    unitId: 'u6',
    unitNumber: '3B',
    leaseStatus: 'active',
    leaseStartDate: '2023-02-15',
    leaseEndDate: '2024-02-15',
    moveInDate: '2023-02-15',
    rentAmount: 1450,
    rentStatus: 'overdue',
    balance: 1450,
    autopayEnabled: false,
    paymentMethod: 'ach',
    maintenanceRequestCount: 1,
    lastMaintenanceRequestDate: '2024-01-05',
    communicationStatus: 'responsive',
    portalStatus: 'accepted',
    documentStatus: 'complete',
    tags: ['renewal_risk'],
    createdAt: '2023-02-01'
  },
  {
    id: 't2',
    name: 'Michael Chen',
    email: 'm.chen@example.com',
    propertyId: 'p2',
    propertyName: 'Highland Lofts',
    unitId: 'u8',
    unitNumber: '102',
    leaseStatus: 'active',
    leaseStartDate: '2023-08-01',
    leaseEndDate: '2024-08-01',
    rentAmount: 2300,
    rentStatus: 'paid',
    balance: 0,
    autopayEnabled: true,
    paymentMethod: 'credit_card',
    lastPaymentDate: '2024-01-01',
    maintenanceRequestCount: 0,
    communicationStatus: 'responsive',
    portalStatus: 'accepted',
    documentStatus: 'complete',
    tags: ['vip'],
    createdAt: '2023-07-15'
  },
  {
    id: 't3',
    name: 'Sarah Johnson',
    email: 's.johnson@example.com',
    propertyId: 'p2',
    propertyName: 'Highland Lofts',
    unitId: 'u10',
    unitNumber: '201',
    leaseStatus: 'month_to_month',
    leaseStartDate: '2023-06-30',
    leaseEndDate: '2024-06-30', // Originally 1 year, now MTM potentially
    rentAmount: 2100,
    rentStatus: 'partial',
    balance: 450,
    autopayEnabled: false,
    paymentMethod: 'ach',
    lastPaymentDate: '2024-01-03',
    maintenanceRequestCount: 0,
    communicationStatus: 'unread',
    portalStatus: 'invited',
    documentStatus: 'complete',
    tags: [],
    createdAt: '2023-06-15'
  },
  {
    id: 't4',
    name: 'David Wilson',
    email: 'dwilson@example.com',
    propertyId: 'p3',
    propertyName: 'Sunset Duplex',
    unitId: 'u11',
    unitNumber: 'A',
    leaseStatus: 'active',
    leaseStartDate: '2023-11-15',
    leaseEndDate: '2024-11-15',
    rentAmount: 1850,
    rentStatus: 'paid',
    balance: 0,
    autopayEnabled: true,
    paymentMethod: 'check',
    lastPaymentDate: '2024-01-01',
    maintenanceRequestCount: 2,
    lastMaintenanceRequestDate: '2023-12-28',
    communicationStatus: 'responsive',
    portalStatus: 'accepted',
    documentStatus: 'complete',
    tags: ['maintenance_heavy'],
    createdAt: '2023-11-01'
  },
  {
    id: 't5',
    name: 'Emily Davis',
    email: 'emily.d@example.com',
    propertyId: 'p1',
    propertyName: 'Oak Street Apartments',
    unitId: 'u1',
    unitNumber: '1A',
    leaseStatus: 'renewal_pending',
    leaseStartDate: '2023-03-01',
    leaseEndDate: '2024-03-01',
    rentAmount: 1200,
    rentStatus: 'paid',
    balance: 0,
    autopayEnabled: true,
    paymentMethod: 'ach',
    lastPaymentDate: '2024-01-02',
    maintenanceRequestCount: 0,
    communicationStatus: 'responsive',
    portalStatus: 'accepted',
    documentStatus: 'lease_signed',
    tags: [],
    createdAt: '2023-02-20'
  },
  {
    id: 't6',
    name: 'Robert Brown',
    email: 'robert.brown@example.com',
    propertyId: 'p1',
    propertyName: 'Oak Street Apartments',
    unitId: 'u2',
    unitNumber: '1B',
    leaseStatus: 'active',
    leaseStartDate: '2023-09-01',
    leaseEndDate: '2024-09-01',
    rentAmount: 1350,
    rentStatus: 'credit',
    balance: -50,
    autopayEnabled: true,
    paymentMethod: 'ach',
    maintenanceRequestCount: 0,
    communicationStatus: 'responsive',
    portalStatus: 'accepted',
    documentStatus: 'complete',
    tags: [],
    createdAt: '2023-08-15'
  },
  {
    id: 't7',
    name: 'Jennifer Wu',
    email: 'j.wu@example.com',
    propertyId: 'p2',
    propertyName: 'Highland Lofts',
    unitId: 'u7',
    unitNumber: '101',
    leaseStatus: 'pending_move_in',
    leaseStartDate: '2024-02-01',
    leaseEndDate: '2025-02-01',
    rentAmount: 2250,
    rentStatus: 'paid', // Deposit paid
    balance: 0,
    autopayEnabled: false,
    maintenanceRequestCount: 0,
    communicationStatus: 'responsive',
    portalStatus: 'invited',
    documentStatus: 'missing_docs',
    tags: ['new_tenant'],
    createdAt: '2024-01-20'
  },
  {
    id: 't8',
    name: 'Kevin O\'Connell',
    email: 'kevin.o@example.com',
    propertyId: 'p3',
    propertyName: 'Sunset Duplex',
    unitId: 'u12',
    unitNumber: 'B',
    leaseStatus: 'eviction',
    leaseStartDate: '2022-05-01',
    leaseEndDate: '2023-05-01', // Held over
    rentAmount: 1900,
    rentStatus: 'overdue',
    balance: 5700, // 3 months
    autopayEnabled: false,
    paymentMethod: 'other',
    maintenanceRequestCount: 5,
    communicationStatus: 'unresponsive',
    portalStatus: 'disabled',
    documentStatus: 'complete',
    tags: ['high_risk', 'legal'],
    createdAt: '2022-04-15'
  }
];
