import { MaintenanceRequest } from '@/shared/types/maintenance';
import { addDays, subDays, subHours } from 'date-fns';

export const MOCK_TENANT_REQUESTS: MaintenanceRequest[] = [
  {
    id: 'req_1',
    unitId: 'unit_3b',
    tenantId: 'tenant_1',
    propertyId: 'prop_sunset',
    title: 'Water leaking from ceiling',
    description: 'There is a steady drip coming from the master bathroom ceiling fan vent. I have placed a bucket underneath.',
    category: 'plumbing',
    priority: 'emergency',
    status: 'in_progress',
    allowEntryWithoutTenant: true,
    preferredAccessTimes: 'Anytime',
    petsPresent: false,
    attachments: [
      {
        id: 'media_1',
        type: 'image',
        url: 'https://placehold.co/600x400/png?text=Leaking+Ceiling',
        uploadedBy: 'tenant',
        uploadedAt: subHours(new Date(), 4).toISOString(),
      }
    ],
    messages: [
      {
        id: 'msg_1',
        requestId: 'req_1',
        senderType: 'tenant',
        message: 'It seems to be getting worse with the rain.',
        createdAt: subHours(new Date(), 3).toISOString(),
      },
      {
        id: 'msg_2',
        requestId: 'req_1',
        senderType: 'manager',
        message: 'We have dispatched a plumber (Mario Bros Plumbing). They should arrive within 2 hours.',
        createdAt: subHours(new Date(), 1).toISOString(),
      }
    ],
    createdAt: subHours(new Date(), 5).toISOString(),
    updatedAt: subHours(new Date(), 1).toISOString(),
  },
  {
    id: 'req_2',
    unitId: 'unit_3b',
    tenantId: 'tenant_1',
    propertyId: 'prop_sunset',
    title: 'Dishwasher not draining',
    description: 'The dishwasher leaves water at the bottom after the cycle finishes.',
    category: 'appliance',
    priority: 'normal',
    status: 'submitted',
    allowEntryWithoutTenant: false,
    preferredAccessTimes: 'Weekdays after 5pm/Weekends',
    petsPresent: true,
    attachments: [],
    messages: [],
    createdAt: subDays(new Date(), 2).toISOString(),
    updatedAt: subDays(new Date(), 2).toISOString(),
  },
  {
    id: 'req_3',
    unitId: 'unit_3b',
    tenantId: 'tenant_1',
    propertyId: 'prop_sunset',
    title: 'Loose railing on balcony',
    description: 'The handrail feels a bit wobbly on the left side.',
    category: 'structural',
    priority: 'high',
    status: 'scheduled',
    allowEntryWithoutTenant: true,
    preferredAccessTimes: 'Anytime',
    petsPresent: false,
    attachments: [],
    messages: [
        {
            id: 'msg_3',
            requestId: 'req_3',
            senderType: 'system',
            message: 'Maintenance scheduled for Jan 24, 2026 at 10:00 AM.',
            createdAt: subDays(new Date(), 1).toISOString(),
        }
    ],
    createdAt: subDays(new Date(), 5).toISOString(),
    updatedAt: subDays(new Date(), 1).toISOString(),
  },
  {
    id: 'req_4',
    unitId: 'unit_3b',
    tenantId: 'tenant_1',
    propertyId: 'prop_sunset',
    title: 'Replace HVAC filter',
    description: 'Regular maintenance request.',
    category: 'hvac',
    priority: 'normal',
    status: 'completed',
    allowEntryWithoutTenant: true,
    preferredAccessTimes: 'Anytime',
    petsPresent: false,
    attachments: [],
    messages: [],
    createdAt: subDays(new Date(), 30).toISOString(),
    updatedAt: subDays(new Date(), 28).toISOString(),
    completedAt: subDays(new Date(), 28).toISOString(),
  },
  {
    id: 'req_5',
    unitId: 'unit_3b',
    tenantId: 'tenant_1',
    propertyId: 'prop_sunset',
    title: 'Fixed Front Door Lock',
    description: 'The lock was sticking, vendor lubricated and adjusted strike plate.',
    category: 'safety',
    priority: 'high',
    status: 'completed',
    allowEntryWithoutTenant: false,
    preferredAccessTimes: 'Weekends',
    petsPresent: false,
    attachments: [],
    messages: [
       {
           id: 'msg_99',
           requestId: 'req_5',
           senderType: 'manager',
           message: 'This has been resolved. Let us know if it sticks again.',
           createdAt: subDays(new Date(), 10).toISOString(),
       }
    ],
    createdAt: subDays(new Date(), 12).toISOString(),
    updatedAt: subDays(new Date(), 10).toISOString(),
    completedAt: subDays(new Date(), 10).toISOString(),
  }
];
